spring:
  application:
    name: play

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo1
      username: root
      password: 123456

server:
  port: 8080